version: '2'
services:
    smartlearnplatform-app:
        image: smartlearnplatform
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartlearnplatform-mysql:3306/smartlearnplatform?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=smartlearnplatform-elasticsearch:9300
        ports:
            - 8080:8080
    smartlearnplatform-mysql:
        extends:
            file: mysql.yml
            service: smartlearnplatform-mysql
    smartlearnplatform-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smartlearnplatform-elasticsearch
